### ISSUE TITLE
#18053

### ISSUE THREAD

**Issue by nayuta-yanagisawa** [nayuta-yanagisawa/tidb#2]
https://github.com/pingcap/tidb/issues/18053

## TODO

- [x] DDL の design doc 読む
- [ ] drop index の PR 読む 
- [ ] add column の PR 読む
- [x] 最低限のテストを追加 
- [ ] add index の execution path を追跡する

## 参考資料

- https://dev.mysql.com/doc/refman/5.7/en/alter-table.html
- adding multiple column https://github.com/pingcap/tidb/pull/15540
- https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md
- 親 issue https://github.com/pingcap/tidb/issues/14766
- dropping multi-indexes https://github.com/pingcap/tidb/pull/20457/

## メモ

- yyy
